version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:23

    steps:
      - checkout

      # Install Bun
      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      
      # Install dependencies
      - run:
          name: Install dependencies
          command: bun install

      # Run build
      - run:
          name: Run build
          command: bun run build

      # Run tests
      - run:
          name: Run tests
          command: bun run test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test